### ISSUE TITLE
netcoreapp3.0 target is not supported since March 3, 2020

### ISSUE THREAD

**Issue by FyiurAmron** [csinkers/ualbion#21]
See https://dotnet.microsoft.com/platform/support/policy/dotnet-core for details. Migration to at least Core 3.1 (LTS, but actual support time is roughly the same as of .NET 5) or .NET 5 preferably (both would be supported until at least 2022) would solve this completely (currently, targetting 3.0 results in a spam of NETSDK1138 warnings).

Official doc: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50 (also https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31 to a lesser extent)

Checking this by fixing the csprojs by hand didn't result in any obvious issues. I can create a PR with these changes if it's the preferred way to handle this, no biggie.

As a side note: if compatibility with Mono/Xamarin is not an issue, using `net5.0` profile consistently instead of e.g. `netstandard2.1` etc.  would be more futureproof.

**Comment by csinkers** [comment]
Ah yup, been meaning to do that. I think I'd left it on 3.0 due to a compiler bug that was introduced in one of the 3.1 releases, that's been resolved now so no reason not to. I'm currently in the middle of a massive refactor of the asset system, but I'll bump the .NET Core version as part of that. Would like to move to 5 at some point as well to take advantage of the new code generation stuff etc, but will need to do some testing first.

**Comment by csinkers** [comment]
Ok, the branch has been merged in with the .NET version update now so closing the issue. Will move to .NET 5 once I've got some time.
